theme: minima
title: ramblings of tiredness and abstraction
twitter_username: onwardsgames
email: aoshima@onwards.games
rss: rss feed

description: onwards is a tiny game development studio based in brazil
minima:
  skin: dark