theme: minima
title: ramblings of tiredness
description: onwards is a tiny game development studio based in brazil
minima:
  skin: dark
  social_links:
    twitter: onwardsgames
    twitter: itsaoshima