theme: minima
title: ramblings of tiredness and abstraction
twitter_username: onwardsgames
youtube_username: "@onwardsgames"
email: aoshima@onwards.games
rss: rss
author: aoshima
staticman_url: https://onwards-games-staticman-5843657dd789.herokuapp.com/v3/entry/github/guipaz/guipaz.github.io/main/comments

description: onwards! is a tiny game development studio based in brazil
minima:
  skin: dark