theme: minima
title: ramblings of tiredness and abstraction
twitter_username1: onwardsgames
twitter_username1: aoshimaon
email: aoshima@onwards.games
rss: rss

description: onwards is a tiny game development studio based in brazil
minima:
  skin: dark