theme: jekyll-theme-minima
title: ramblings of tiredness and abstraction
description: onwards is a tiny game development studio based in brazil
minima:
  skin: dark
  social_links:
    - { platform: twitter,  user_url: "https://twitter.com/onwardsgames" }
    - { platform: twitter,  user_url: "https://twitter.com/itsaoshima" }